name: Testing with TestCafe

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Start React app
        run: |
          npm run dev &
          sleep 30
          

      - name: Run TestCafe tests
        run: npx testcafe chrome:headless src/tests/ --no-sandbox --disable-setuid-sandbox
