name: Testing with TestCafe

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Start React app
        run: |
          npm run dev &> react_app.log &
          sleep 10
          cat react_app.log
          npx wait-on http://localhost:5173

      - name: Run TestCafe tests
        run: npx testcafe "chrome:headless --no-sandbox" src/tests/ --hostname localhost --retry-test-pages --page-request-timeout 10000