name: Testing with TestCafe

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install

    # Start the React app in the background
    - name: Start React app
      run: npm run dev &

    - name: Check server status
      run: curl -I http://localhost:5173

    # Run TestCafe tests
    - name: Run TestCafe tests
      run: npx testcafe "chrome:headless --no-sandbox" src/tests/ --hostname localhost --retry-test-pages --page-request-timeout 10000